config/routes.rb
Tohash::Application.routes.draw do |map|
  
  match '/new' => 'tuples#new', :as => :new_hash
  match '/:id(.:format)' => 'tuples#show', :as => :hash
  resources :tuples
  root :to => "home#index"
  

end

app/models/tuple.rb
class Tuple < ActiveRecord::Base
  
  serialize :content
  
  before_save :convert_hashes
  def convert_hashes
    self.md5 = to_md5
    self.sha1 = to_sha1
    self.sha2 = to_sha2
  end
  
  def to_md5
    self.class.md5(content.to_yaml)
  end
  
  def to_sha1
    self.class.sha1(content.to_yaml)
  end
  
  def to_sha2
    self.class.sha2(content.to_yaml)
  end
  
  def to_param
    sha2
  end
  
  def to_csv
    r = []
    for k,v in content
      r << [k,v].join(",")
    end if content.is_a?(Hash)
    r.join("\n")
  end
  
  class << self
    def sha2(str)
      Digest::SHA2.hexdigest(str)
    end
    
    def sha1(str)
      Digest::SHA1.hexdigest(str)
    end
    
    def md5(str)
      Digest::MD5.hexdigest(str)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @sample_hash = Tuple.first
  end

end

app/controllers/tuples_controller.rb
class TuplesController < ApplicationController
  def show
    
    @tuple = case params[:id].size
    when 64
      Tuple.find_by_sha2(params[:id])
    when 40
      Tuple.find_by_sha1(params[:id])
    when 32
      Tuple.find_by_md5(params[:id])
    else
      Tuple.find(params[:id])
    end
    
    respond_to do |format|
      format.html
      format.xml { render :xml => @tuple }
      format.yaml { render :text => @tuple.content.to_yaml }
      format.text { render :text => @tuple.content.to_yaml }
      format.csv { render :text => @tuple.to_csv }
    end
  end
  
  def new
    options = params.except(:action, :controller)
    unless @tuple = Tuple.find_by_sha2(Tuple.sha2(options.to_yaml))
      @tuple = Tuple.create(:content => options)
    end
    respond_to do |format|
      format.html { redirect_to "/#{@tuple.to_param}" }
      format.xml { render :xml => @tuple, :status => :created, :location => hash_url(@tuple.sha2) }
    end
    
  end

  def create
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def sample_hash_url(format=nil)
    %Q{56bbdda335500fc38e1c10458f2e5865e1927c5978e9b0a3667db67196fc77dc#{".#{format}" if format}}
  end
end

app/helpers/tuples_helper.rb
module TuplesHelper
end

app/views/home/index.html.haml
%article
  
  %h2 Creating a new Hash
  
  %p
    HTTP GET 
    %tt http://tohash.com/new
    followed by your query string. This will create a new hash record, saving the contents of your query string as key/value pairs. You can later reference the key/value pairs simply by visiting your hash's URL. 
  %h3 Example
  %p
    = link_to new_hash_url(@sample_hash.content), new_hash_url(@sample_hash.content)
    / %a{:href => "/new?#{@sample_hash.content.to_param}"}= "http://tohash.com/new?#{@sample_hash.content.to_param}"

%article
  %h2 Accessing your Hash
  %p
    Just visit your hash's unique URL in your browser. You can also reference your hash via the API (see below) for use in your apps.
    
  %h3 Example
  %p
    = link_to hash_url(@sample_hash.sha2), hash_url(@sample_hash.sha2)
  
  %p Your hash can be referenced using SHA2, SHA1, or trusty old MD5:
  
  %h4 SHA2
  = link_to hash_url(@sample_hash.sha2), hash_url(@sample_hash.sha2)
  %h4 SHA1
  = link_to hash_url(@sample_hash.sha1), hash_url(@sample_hash.sha1)
  %h4 MD5
  = link_to hash_url(@sample_hash.md5), hash_url(@sample_hash.md5)

%article
  %h2 API
  %p You can also get the hash values in many different formats: 
  %h4 XML
  = link_to hash_url(@sample_hash, :format => :xml), hash_url(@sample_hash, :format => :xml)
  %h4 YAML
  = link_to hash_url(@sample_hash, :format => :yaml), hash_url(@sample_hash, :format => :yaml)
  %h4 CSV
  = link_to hash_url(@sample_hash, :format => :csv), hash_url(@sample_hash, :format => :csv)
  

app/views/layouts/_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-175340-24']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/application.html.haml
!!!
%html{ :lang => "en" }
  %head
    %title Tohash
    = csrf_meta_tag
    
    %link{:href => "/stylesheets/all.css", :media => "all", :rel => "stylesheet"}
    <![if !IE]><link rel="stylesheet" href="/stylesheets/advanced.css" media="screen and (min-device-width: 750px)" class="lf-advanced"/><![endif]>
    /[if gt IE 6] 
      %link{:href => "/stylesheets/advanced.css", :media => "screen and (min-device-width: 750px)", :rel => "stylesheet", :class => "lf-advanced"}
    /[if IE]
      %script{:src => "/javascripts/html5.js"}
    %link{:href => "/stylesheets/tohash.css", :media => "all", :rel => "stylesheet"}
    = render :partial => "layouts/analytics"
  %body
    .container
      %header
        %h1.first
          %a{:href => "/"}
            Tohash
            %small
              \ {:to =&gt :hash}
      = yield

      %footer
        %p
          A small project by 
          %a{:href => "http://mysmallidea.com"} 
            %img{:src => "/images/the-small-idea-company.png", :alt => "The Small Idea Company"}
      .clear
    
    %a{:href => "http://github.com/mysmallidea/Tohash"}
      %img{:alt => "Fork me on GitHub", :src => "http://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png", :style => "position: absolute; top: 0; right: 0; border: 0;"}/

app/views/tuples/show.html.haml
%article
  %h1 
    Stored Values for
    = params[:id]

  %table
    %thead
      %tr
        %th Key
        %th Value
    %tbody
      - for k,v in @tuple.content
        %tr
          %th= k
          %td= v

%article
  %h1 Hashes
  %table
    %thead
      %tr
        %th Scheme
        %th Hash
    %tbody
      %tr
        %th SHA2
        %td= link_to @tuple.sha2, @tuple
      %tr
        %th SHA1
        %td= link_to @tuple.sha1, url_for(@tuple.sha1)
      %tr
        %th MD5
        %td= link_to @tuple.md5, url_for(@tuple.md5)
      
  
%article
  %h2 Help
  %a{:href => "/"} How to save a new hash